### ISSUE TITLE
GCS does not refresh OAuth2 tokens

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1109]
**Problem**

The GCS Sink uses `auth::json_api_client` which in turn called `authenticate_bearer` which in turn fetches a OAuth2 token. This happens during startup time meaning the token is not re-generated or refreshed. Part of the OAuth flow is that tokens have a limited lifetime and require periodic refresh.

I am not sure what the times for google oauth tokens are but they probably range from hours to days so this is nothing we would have seen in tests, that said in production the current GCS sink will eventually fail to authenticate and throw errors, this will be very confusing to users.

**Possible Solution(s)**

Fortunately `Token` from `gouth` handles this logic for us. If it is cached and `header_value` is called on reach request it will take the token lifetime into account and request a new bearer token whenever the current one is outdated.

**Comment by dak-x** [comment]
Creating a wrapper struct around the client and some refactor in `storage.rs` won't be an issue I presume. I see that @jigyasak05 wrote this, since Im not aware if this is still under active development, would changing the client type break something you might be working on?
I ll look for ways to include this inside the client itself.

**Comment by jigyasak05** [comment]
I don't think that should be a problem👍
