### ISSUE TITLE
Build always uses AVX2 instructions

### ISSUE THREAD

**Issue by risicle** [tremor-rs/tremor-runtime#1221]
**Problem**
You quite possibly don't consider this much of an issue as non-AVX2 processors are becoming increasingly irrelevant, but I thought I should note anyway -

0.11.6 (and 0.11.5 at least), built on x86_64 linux with rust 1.54.0, LLVM 12.0.1, when `tremor --test-threads=4` is run on a non-AVX2 machine will result in a SIGILL.

I'm fairly sure this is a **separate** issue from that you note about `simd-json`.

Backtrace:

```
 ► f 0     55555755498e linked_hash_map::LinkedHashMap<K,V,S>::insert+78
   f 1     555557551fa6 yaml_rust::yaml::YamlLoader::insert_new_node+1014
   f 2     55555755179f
   f 3     555557546c28 yaml_rust::parser::Parser<T>::load_node+312
   f 4     555557546f27 yaml_rust::parser::Parser<T>::load_node+1079
   f 5     55555754673e yaml_rust::parser::Parser<T>::load+1518
   f 6     555557552140 yaml_rust::yaml::YamlLoader::load_from_str+160
   f 7     55555655ec37 tremor::main+55
   f 8     55555660bd23 std::sys_common::backtrace::__rust_begin_short_backtrace+3
   f 9     55555660c3e5 _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h6b3754768d1586d4E.llvm.14889178757154111219+21
   f 10     55555638d417 std::rt::lang_start_internal+135
```

This is due to the use of a `vpermq` instruction.

```
Dump of assembler code for function _ZN15linked_hash_map30LinkedHashMap$LT$K$C$V$C$S$GT$6insert17h691937e6791e866cE:
   0x0000555557554940 <+0>:     push   rbp
   0x0000555557554941 <+1>:     mov    rbp,rsp
   0x0000555557554944 <+4>:     push   r15
   0x0000555557554946 <+6>:     push   r14
   0x0000555557554948 <+8>:     push   r13
   0x000055555755494a <+10>:    push   r12
   0x000055555755494c <+12>:    push   rbx
   0x000055555755494d <+13>:    and    rsp,0xffffffffffffffe0
   0x0000555557554951 <+17>:    sub    rsp,0x140
   0x0000555557554958 <+24>:    mov    r12,rcx
   0x000055555755495b <+27>:    mov    r15,rdx
   0x000055555755495e <+30>:    mov    r13,rsi
   0x0000555557554961 <+33>:    mov    rbx,rdi
   0x0000555557554964 <+36>:    cmp    QWORD PTR [rsi+0x30],0x0
   0x0000555557554969 <+41>:    jne    0x555557554986 <_ZN15linked_hash_map30LinkedHashMap$LT$K$C$V$C$S$GT$6insert17h691937e6791e866cE+70>
   0x000055555755496b <+43>:    mov    edi,0x8
   0x0000555557554970 <+48>:    mov    esi,0xa0
   0x0000555557554975 <+53>:    call   QWORD PTR [rip+0xb55fb5]        # 0x5555580aa930
   0x000055555755497b <+59>:    mov    QWORD PTR [r13+0x30],rax
   0x000055555755497f <+63>:    mov    QWORD PTR [rax],rax
   0x0000555557554982 <+66>:    mov    QWORD PTR [rax+0x8],rax
   0x0000555557554986 <+70>:    mov    QWORD PTR [rsp+0xd8],rbx
=> 0x000055555755498e <+78>:    vpermq ymm0,YMMWORD PTR [r13+0x0],0x50
   0x0000555557554995 <+85>:    vmovdqu xmm1,XMMWORD PTR [r13+0x0]
   0x000055555755499b <+91>:    vpxor  ymm0,ymm0,YMMWORD PTR [rip+0x18a67d]        # 0x5555576df020
   0x00005555575549a3 <+99>:    vpxor  xmm2,xmm2,xmm2
   0x00005555575549a7 <+103>:   vmovdqu XMMWORD PTR [rsp+0x58],xmm2
```

**Comment by Licenser** [comment]
Hi,

yes and no. We build explicitly for the most common subset of CPU features. `AVX`, `AVX2` and `SSE4.2`. This is set in the `.cargo/config`:

```toml
[build]
rustflags = ["-C", "target-feature=+avx,+avx2,+sse4.2"]
```

it is possible to change this , AVX2 isn't strictly required, but it makes things faster, (SSE4.2 in contrast is strictly required as it's the minimal instruction set for simd-json). That said it wouldn't make a sense for the project itself, AVX2 has been in CPUs for 10+ years by now so hurting performance for the majority for users to allow some edge cases feels wrong.

That said @mfelsche hat the nice observation that nix builds everything locally on the machine, so setting

```
RUSTFLAGS="-C target-cpu=native" cargo
```

will optimize for the exact CPU and if no AVX2 is available still work, if AVX2 is available make use of that and if rust can throw in some more advanced instructions because it's a shiny new CPU go and use those.

It won't make sense for packages as then everyone is bound to the CPU the CI machine runs, but if nix builds the binary on the same machine it runs, `cpu-target=native` seems like a good way.

**Comment by risicle** [comment]
Fair enough, thanks for this.
