### ISSUE TITLE
HTTP connector config is unclear about how codecs interact

### ISSUE THREAD

**Issue by happysalada** [tremor-rs/tremor-runtime#2083]
**Problem**
I’m sure I’ve missed something, but after re-reading several times, I still can’t see it.
I’ve got the following connector
```
  define connector `http_in` from http_client
  with
    preprocessors = ["separate"],
    codec = "csv",  # Defaults to HTTP codec
    config = {
      "url": "https://www.cer-rec.gc.ca/open/imports-exports/crude-oil-exports-by-type-monthly.csv",
      "tls": true,
    }
  end;
```
I’ve verified that the file is actually csv, however whenever I run tremor, I get the following error 
```
"2022-11-20T23:12:20.600612414+00:00 ERROR tremor_runtime::connectors - [Sink::http_in] Error serializing event into request body: The value Object cannot be serialized to CSV. Expected an array.”
```

**Possible Solution(s)**
Here is the full file I am using, just in case
```
define flow canada_crude_exports
flow
  use tremor::connectors;
  use tremor::pipelines;

  define connector every_hour from metronome
  with
     config = {"interval": 1000}
  end;

  define connector `http_in` from http_client
  with
    preprocessors = ["separate"],
    codec = "csv",  # Defaults to HTTP codec
    config = {
      "url": "https://www.cer-rec.gc.ca/open/imports-exports/crude-oil-exports-by-type-monthly.csv",
      "tls": true,
    }
  end;

  define pipeline canada_crude_exports
  pipeline

    define script canada_crude_export
    # sample
    # 06/01/1985,1985,June,Light,28019.093333,176320.147616320000
    script
      use std::array;
      use std::type;
      use std::re;
      match event of
        case %["Period", _, _, _, _, _] => drop
        case %[start_date, _, _, type, m3_day, bbl_day] =>
          match type::is_null(state) of
            case true =>
              let state = [[start_date, type]]
            default =>
              match array::contains(state, [start_date, type]) of
                case true => drop
                default => array::push(state, [start_date, type])
              end
          end;
          let date_array = re::split("/", start_date);
          let day = date_array[0];
          let month = date_array[1];
          let year = date_array[2];
          emit {
            "from": "#{year}-#{month}-#{day}T00:00:00Z",
            "frequency": "monthly",
            "type": type,
            "volume": {
              "m3_day": m3_day,
              "bbl_day": bbl_day
            }
          }
        default => drop
      end;
    end;

    create script process from canada_crude_export;
  
    select event from in into process;
    select event from process into out;
  end;

  define connector influx_out from http_client
  with
    codec = "influx",
    # configure the endpoint we're writing to
    config = {
      "url": "http://127.0.0.1:8086/write?db=test",
      # We use a custom header to identify that we're tremor
      "headers": {"Client": ["Tremor"]}
    }
  end;

  create connector every_hour from every_hour;
  create connector http_in from http_in;
  create connector influx_out from influx_out;
  create pipeline passthrough from pipelines::passthrough;
  create pipeline process from canada_crude_exports;

  connect /connector/every_hour to /pipeline/passthrough;
  connect /pipeline/passthrough to /connector/http_in;
  connect /connector/http_in to /pipeline/process;
  connect /pipeline/process to /connector/influx_out;
  # connect /pipeline/process to /connector/surreal_out;
end;
```

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor --version`:

**Comment by Licenser** [comment]
Thanks for the well thought out and documented issue! we'll take a look right away

**Comment by Licenser** [comment]
So after some investigation the short:

1) good catch thank you ❤️ 
2) it's a bug 🐛 
3) it's not the CSV codec but the http  connector. 😨 

the long:

## What happens

Two things happen here:

First one is the error you see, the metronome sends a struct, then the `http_client` as it is configured as `codec = "csv"` will try to encode this struct as a CSV value and fails.

The second one is and this is where Mr. Bug comes in, that the server replies with `content-type: application/octet-stream` which triggers the HTTP client to decode the data as a octet-stream instead of csv. Now this is a bug, as it's nasty, and totally not what one would expect.

## Quick Fix

I personally find this super counter-intuitive as a solution so your code was, while it technically did not work, right in the sense that it's what a one would expect to write.

```troy
 define connector `http_in` from http_client
  with
    preprocessors = ["separate"],
    config = {
      "url": "https://www.cer-rec.gc.ca/open/imports-exports/crude-oil-exports-by-type-monthly.csv",
      "method": "get",
      "tls": true,
      "custom_codecs": {
        "application/octet-stream": "csv"
      }
    }
  end;
```

This definition is working and changes three things:

1) it introduces `"method": "get"` otherwise, we'd send post requests and the server doesn't like that.
2) it removes the `codec` part, letting the requests arriving from the metronome to be encoded as JSON (not that it matters for a GET anyway)
3) it introduces the `custom_codecs` to tell the client that when we receive an `octet-stream` header from the server we really really want to decode it as csv


So with that you can keep going, yay!

## Next steps

We'll have to think to make codec handling for HTTP more intuitive as this really shouldn't be this complicated :)

**Comment by happysalada** [comment]
Thanks a lot for the very quick answer!

**Comment by Licenser** [comment]
@happysalada I would love your input on the solution we came up with to make this clearer.

Here are the [docs update](https://github.com/tremor-rs/tremor-www/pull/272) as well as the related [PR](https://github.com/tremor-rs/tremor-runtime/pull/2088)

the short is the `http` connectors no longer take a codec but instead handle their encoding via mime-types with the option to specify a `*/*` mime-type as a catch all.

**Comment by happysalada** [comment]
This looks good, thank you for the quick fix !
