### ISSUE TITLE
`http` stdlib module

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#2183]
**Describe the problem you are trying to solve**

Make dealing with http in tremor easier, especially the `http` connectors: https://www.tremor.rs/docs/edge/reference/connectors/http

**Describe the solution you'd like**

An `http` module in the standard library.
It should contain:
* a submodule with common header names as constants: `std::http::headers`.
* a submodule with method names as constants: `std::http::methods`
* a submodule with common content-types as constants.
* a submodule with common status numbers and messages as constants.

And whatever you think is useful.

**Comment by 0xquark** [comment]
Hi @mfelsche , I'd like to work on this issue. Could you brief me more about it ?

**Comment by Licenser** [comment]
Heya,

we try to supply utility functions as part of the tremor [standard library](https://www.tremor.rs/docs/edge/reference/stdlib/).  The goal is to have have `http` and related constants as part of the standard library. Matthias did detail some of the things that'd be nice to import.

To give an example or two.

instead of using `"content-type"` as a header it'd be nice to have a constant `http::headers::CONTENT_TYPE` that expands to it, instead of `200` it'd be nice to have a constant `http::status::OK` and so on.

we have something similar for google cloud logging: https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-script/lib/google/cloud/logging/severity.tremor

**Comment by 0xquark** [comment]
Thanks @Licenser! Yes, having http and related constants as part of the standard library would definitely make dealing with http in Tremor easier. However could you help me knowing where should i add the module in the tremor-runtime?

**Comment by Licenser** [comment]
Heya,

I'd start in https://github.com/tremor-rs/tremor-runtime/tree/main/tremor-script/lib we have google, cncf and some other high levels consts there, so I'd follow the same structures so something like `lib/http/methods.tremor` and so on :)
