### ISSUE TITLE
investigate eyre as a replacement for error chain

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#389]
Error chain is starting to become more and more depricated and no longer the defacto-error handling library in rust. One of the promising alternatives that seems to have an active community that drives it forward is [erey](https://github.com/yaahc/eyre) we should investigate if we can replace our use of error-chain with this.

**Comment by aryan9600** [comment]
A couple of alternatives to `eyre` are [`thiserror`](https://github.com/dtolnay/thiserror) and [`anyhow`](https://github.com/dtolnay/anyhow).
* `anyhow` is better for us than `thiserror`
>Use Anyhow if you don't care what error type your functions return, you just want it to be easy. This is common in application-like code. https://github.com/dtolnay/thiserror#comparison-to-anyhow

`anyhow` does seem to be more actively maintained than `eyre` which can be crucial, since we are moving from `error_chain` due to it's lack of maintenance.

**Comment by Licenser** [comment]
One of the things I see in `eyre` and `anyhow` that could be an advantage is they include error context/trace/origin. That is not something we do use too little but is worth thinking about.

**Comment by darach** [comment]
AFAIU this can now be closed as we have since settled on thiserror with anyhow. Closing.
