### ISSUE TITLE
Ability to use Extractors outside of patterns

### ISSUE THREAD

**Issue by ceosion** [tremor-rs/tremor-runtime#395]
**Describe the problem you are trying to solve**
Extractors offer a lot of good functionality like the ability to convert a string of JSON into a [JSON](https://docs.tremor.rs/tremor-script/extractors/json/) object/record, or the ability to [Dissect](https://docs.tremor.rs/tremor-script/extractors/dissect/) parts of some string into constituent parts. But they are currently limited to use only in patterns within match/case blocks.

**Describe the solution you'd like**
The ability to use Extractors outside of just patterns in match/case blocks. Perhaps something like the ability to simply assign the output of the extractor to a field like so:

```tremor-script
let event.message = { "test": "{ foo:bar, snot:badger }" }
let foobar = %{ event.message ~= json|| };
```
_Just an example, please consider as pseudo-code!_

**Comment by anupdhml** [comment]
An alternative can be to have function equivalents for all extractors, like how we had for datetime parsing:

https://docs.tremor.rs/tremor-script/extractors/datetime/ 
https://github.com/wayfair-tremor/tremor-www-docs/blob/v0.7.0/docs/tremor-script/functions/datetime.md

**Comment by Licenser** [comment]
Hi, yes we've been thinking about that it comes with a few complications. Part of extractors is their characteristic of matching, all of them have the ability to fail a pattern.

To take the example above (ignoring syntax) it creates a problem when `event.message` isn't a JSON.

It could return `false` or `null` but both of them also could be returned from a valid JSON so that's not really a good solution.

Alternatively, the script could simply fail that would be a safer option and perhaps make sense together with some kind of error handling as in #394?

**Comment by Licenser** [comment]
I've been thinking about this a bit and am wondering if there is an easier improvment possible without introducing a type system.

Would lifting extractors from inside of a pattern to a pattern give you the tools you need to achive this? In other words something like:

```
let foobar = match "{ foo:bar, snot:badger }" of
  case res = json|| => res,
  default => null
end;
```

**Comment by ceosion** [comment]
Allowing extractors to be used as described above does help, I think!

**Comment by Licenser** [comment]
The suggested improvement is implemented.
