### ISSUE TITLE
Support headers for kafka source and sink

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#737]
**Describe the problem you are trying to solve**

Newer versions of Kafka support message headers, we should have a way in tremor to inspect, add, remove and modify them.

**Describe the solution you'd like**

In line with the REST and ES offramp, hearers should be treated as metadata in their own sub-field. We could use:

```tremor
let $kafka = {"header1": "value", "h2":"..."};
```

**Notes**

* [Kafka Headers](https://kafka.apache.org/20/javadoc/index.html?org/apache/kafka/connect/header/Header.html#:~:text=A%20Header%20is%20a%20key,This%20is%20an%20immutable%20interface.)
* [librdkafka-rs interface](https://docs.rs/rdkafka/0.25.0/rdkafka/message/trait.Message.html#tymethod.headers)

**Comment by aryan9600** [comment]
Hey! I have been trying to work on this. This is my first issue, so it'd be if great I got some insight.

If we follow this approach, all our header key/val pairs will be available in the `$kafka` meta variable, but when we are writing a message to a Kafka node, do we want to unpack all the key/val pairs and thus have multiple headers for that message, or just have one header for that message with the key as `kafka` and the value as some `OwnedValue`?
If we want the latter, it looks like we would have to modify `OwnedValue` to implement the `ToBytes` trait defined by [librdkafka-rs](https://github.com/fede1024/rust-rdkafka/blob/master/src/message.rs#L595).
Kindly let me know if this makes sense :)

Thanks
Sanskar

**Comment by anupdhml** [comment]
Hi @aryan9600, thanks for picking this up! Each key-value pair specified in the meta variable here should be treated as a separate header for the message so we do need to iterate through all the entries in the meta variable and add multiple headers for the message.

For the kafka sink, we already have support for [`$kafka_key`](https://docs.tremor.rs/artefacts/offramps/#kafka) as a meta variable, so you may use that as a starting point for your implementation here. For consistency with the existing variable name, let's use something like `$kafka_headers` here (instead of `$kafka`) -- long-term, we should perhaps nest these both under top level `$kafka` which has entries like `key` and `headers`, but
 that sort of cleanup is something we need to do for meta-variables elsewhere too (eg: in the elastic offramp).

On the source side, any headers associated with the message should be collected in a meta-variable of the same name as the one chosen for kafka sink. There's no precedence for this in the kafka source, but the [rest source](https://docs.tremor.rs/artefacts/onramps/#rest) does something similar
 which you can look at for inspiration.

Please let us know if anything else is not clear. Happy hacking!

**Comment by Licenser** [comment]
It'd make some sense to start consolidating new headers into `$kafka.headers` instead of `$kafka_headers` it'll make the transition to a combined `$kafka` easier down the road. It might even make sense to
