### ISSUE TITLE
Interesting wal issue discovered with locking in CI system

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#862]
**Problem**

Reporting for @mfelsche who discovered this odd condition in CI:

```
---- op::qos::wal::test::restart_wal_regression stdout ----
error: test failed, to rerun pass '-p tremor-pipeline --lib'
Error: Error(Sled(Io(Custom { kind: Other, error: "could not acquire lock on \"/tmp/tremor-pipeline-walwhF1jm/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
thread 'op::qos::wal::test::restart_wal_regression' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/test/src/lib.rs:192:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which hasn't manifested locally.

**Steps**

1. Rare issue that crops up in CI environment... wait for it!

**Possible Solution(s)**

Needs investigation!

**Comment by Licenser** [comment]
I think this is more of an incomplete test than a bug. The test in question tries to emulate restart behavior without restarting. So the asynchronous shutdown code of sled isn't finished but the time the next instance is created.

In the case of a shutdown/restart the lock in question would be lost since the locking process would be gone.

I'm not sure how we should solve this on a test level, but we should, flappy tests are terrible :sob:

**Comment by Licenser** [comment]
this is fixed
